name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NASM
        run: choco install nasm -y

      - name: Assemble BIN
        run: nasm -f bin code.asm -o code.bin

      - name: Assemble EXE object
        run: nasm -f win64 program.asm -o program.obj

      - name: Link EXE
        shell: cmd
        run: |
          gcc program.obj -o program.exe -nostdlib -lkernel32 -Wl,--subsystem,console

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            code.bin
            program.exe
