#name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install NASM
        shell: powershell
        run: choco install nasm -y

      - name: Assemble
        shell: cmd
        run: nasm -f win64 asm.asm -o asm.obj

      - name: Build DLL
        shell: cmd
        run: link /DLL /NOENTRY /DEF:asm.def /OUT:asm.dll asm.obj

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: windows-dll
          path: asm.dll
